Matchmaking Redis Data Model: {
  grid-rows: 2

  DefaultQueue: {
    shape: rectangle
    label: "matchmaking-queue"
    type: "Sorted List"
    description: "Queue of user IDs waiting for random matches, \nsorted by the time of entering queue"
  }

  InviteQueue: {
    shape: rectangle
    label: "matchmaking-queue:{queueId}"
    type: "Sorted List"
    description: "Queue of user IDs waiting in specific invite-based match, \nsorted by the time of entering queue"
  }

  SocketMapping: {
    shape: rectangle
    label: "{userId}:socketId"
    type: "String"
    description: "Socket.IO connection ID for user"
  }

  QueuedPlayer: {
    shape: rectangle
    label: "player:{userId}"
    type: "Hash"
    fields: |md
      - queueTimestamp
      - elo
      - queueId
    |
  }
}
